def erro(x):
  return x
